In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import pandas as pd

In [23]:
a = np.array([1, 2, 3, 4],
             )

In [25]:
print(a)

[1 2 3 4]


In [42]:
b = np.array([[0, 0, 0, 1, 2, 3],
              [0, 0, 1, 4, 5, 6],
              [1, 1, 1, 7, 8, 9]])

In [43]:
r, c = np.where(b)

In [44]:
r,c

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int64),
 array([3, 4, 5, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int64))

In [39]:
b[1:3][1:3]

array([[7, 8, 9]])

In [50]:
def calc_size_kb(n,m):
    a = np.random.rand(n,m)
    return a.nbytes/1024

In [51]:
calc_size_kb(5, 6)

0.234375

In [58]:
b = np.array([1, 3, 4, 5, 6, 7])
b[::-1]

array([7, 6, 5, 4, 3, 1])

In [55]:
A = np.array([[1, 2, 3],
              [2, 3, 4],
              [5, 2, 6]])

B = np.array([[1, 2, 3],
              [2, 3, 4],
              [5, 2, 6]])

np.all(A == B)

True

In [59]:
A == B

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [61]:
data = pd.read_csv(r"E:\itac\module1\files\files\adult_data.csv")

In [69]:
data.head().to_string(columns = ['workclass', 'education'], header=False)

'0         State-gov  Bachelors\n1  Self-emp-not-inc  Bachelors\n2           Private    HS-grad\n3           Private       11th\n4           Private  Bachelors'

In [70]:
data[['workclass', 'education']].describe()

workclass education
count      32561     32561
unique         9        16
top      Private   HS-grad
freq       22696     10501

In [3]:
a = [[3, 1, 0],
     [2, 4, 5],
     [0, 2, 3]]
np.linalg.inv(a)

LinAlgError: Singular matrix

In [7]:
def cosine(a, b):
    return np.dot(a, b)/(np.linalg.norm(a)*np.linalg.norm(b))

In [8]:
vec1 = [1, 17, 4, 35]
vec2 = [9, 25, 2, 6]
cosine(vec1, vec2)

0.6100853363130642

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32
)

In [12]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [13]:
coss = [cosine(next_user_stats, i) for i in users_stats]

In [14]:
coss

[0.19999999999999996,
 0.8451542547285165,
 0.3999999999999999,
 0.7905694150420948,
 0.3999999999999999,
 0.0,
 0.0,
 0.9486832980505138,
 0.0,
 0.0]